### ISSUE TITLE
[FEAT] 디자인 수정 구현

### ISSUE THREAD

**Issue by jumining** [SWHackathon2022-Hermes/Client-iOS#25]
## 📌  Feature Issue

 디자인 수정된대로 수정하겠습니당

## 📝  To-do

- [ ] 말풍선 크기 조절
- [ ] 보내기 버튼 그림자 삭제
- [ ] 하단 탭바 길이와 둥글기 수정
- [ ] 검색창 버튼 수정
